[package]
name = "clever-cloud-test"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.8.1"
fred = { version = "10.0.4", features = ["enable-native-tls"] }
tokio = { version = "1.43.0", features = ["full"] }
